### ISSUE TITLE
migration du contenu du .com

### ISSUE THREAD

**Issue by sogilisrc** [sogilis/sogilis.com#25]
**Is your feature request related to a problem? Please describe.**
non, toujours dans une logique d'optimisation du référencement des 2 sites internet

**Describe the solution you'd like**
migrer le contenu actuel du .com vers sogilis.com/en/

**Comment by JulioJu** [comment]
@sogilisrc je de schedule ce ticket. 

Ce ticket est en conflit avec #26 . 

En effet, on ne peut pas à la fois ne pas publier le contenu des pages anglaises et les servir au lien https://sogilis.com/en . On le fera quand tu décideras de les republier.

**Comment by JulioJu** [comment]
Plus d'actualité. Je clos.
