### ISSUE TITLE
mauvais référencement sur google 

### ISSUE THREAD

**Issue by sogilisrc** [sogilis/sogilis.com#36]
**Describe the bug**
![image](https://user-images.githubusercontent.com/83299774/124291351-c728ae80-db54-11eb-9c39-19b1adc317e4.png)

depuis que la redirection du .com vers le .com/fr a été faite, le référencement sur la page google n'est plus optimal
possible de mettre un no index sur cette page ?

**Comment by bdumas1** [comment]
J'ai rajouté un `noindex` `nofollow`. A voir si ça corrige le problème.

**Comment by JulioJu** [comment]
@bdumas1 @sogilisrc problème fixé . Je viens de tester. 

Je clos donc.

**Comment by JulioJu** [comment]
@bdumas1 il ne fallait pas utiliser `nofollow` .

> nofollow | Do not follow the links on this page. If you don't specify this directive, Google may use  the links on the page to discover those linked pages. 
> https://developers.google.com/search/docs/advanced/robots/robots_meta_tag
