### ISSUE TITLE
Change repository description

### ISSUE THREAD

**Issue by JulioJu** [sogilis/sogilis.com#8]
Bonjour,

Il semblerait que le site internet ait été mis en production. La headline de description « Début de refonte du site sogilis.com (début de l'ère post-wordpress)  » à https://github.com/sogilis/sogilis.com est peut-être un peu dépassée ? Peut-être faudrait-il mieux mettre simplement « English Sogilis website », à l'image de ce qui est fait à https://github.com/sogilis/sogilis.fr ?

Qu'en pensez-vous :-) ?

Bonne journée :-)

**Comment by JulioJu** [comment]
@jibidus :-)

**Comment by jibidus** [comment]
Oui, très bonne idée, go go go.

**Comment by JulioJu** [comment]
Done . :-)
